### ISSUE TITLE
Running "python3.8 app.py -t index" or "python3 app.py -t index"

### ISSUE THREAD

**Issue by OSINTAI** [ArturTan/transformers-for-lawyers#2]
I have setup the tool and run the "python3.8 app.py -t index" command and this is the result:

OS: (Ubuntu18)

```
           JINA@7561[E]:theses modules or classes can not be imported ['jina.drivers.querylang.queryset', 'jina.drivers.encode', 'jina.drivers.querylang.queryset.dunderkey', 'jina.drivers.search', 'jina.drivers.control', 'jina.drivers.helper', 'jina.drivers.index', 'jina.drivers.querylang.reverse', 'jina.drivers.querylang.sort', 'jina.drivers.querylang', 'jina.drivers.querylang.filter', 'jina.drivers.convert', 'jina.drivers.rank', 'jina.drivers.craft', 'jina.drivers.reduce', 'jina.drivers.querylang.slice', 'jina.drivers.querylang.queryset.lookup', 'jina.drivers.querylang.select', 'jina.drivers.querylang.queryset.helper']. You can use `jina check` to list all executors and drivers
           JINA@7561[E]:theses modules or classes can not be imported ['jina.executors.clients.BaseClientExecutor', 'jina.executors.clients.BaseExecutor', 'jina.executors.clients.BaseTFServingClientExecutor', 'jina.executors.indexers.vector.BaseNumpyIndexer', 'jina.executors.indexers.vector.BaseVectorIndexer', 'jina.executors.indexers.vector.NumpyIndexer', 'jina.executors.encoders.tfserving.BaseEncoder', 'jina.executors.encoders.tfserving.BaseTFServingClientEncoder', 'jina.executors.encoders.tfserving.BaseTFServingClientExecutor', 'jina.executors.encoders.tfserving.UnaryTFServingClientEncoder', 'jina.executors.encoders.numeric.BaseNumericEncoder', 'jina.executors.encoders.numeric.TransformEncoder', 'jina.executors.rankers.BaseExecutor', 'jina.executors.rankers.BaseRanker', 'jina.executors.rankers.Chunk2DocRanker', 'jina.executors.compound.BaseExecutor', 'jina.executors.compound.CompoundExecutor', 'jina.executors.crafters.BaseCrafter', 'jina.executors.crafters.BaseExecutor', 'jina.executors.crafters.BaseSegmenter', 'jina.executors.indexers.keyvalue', 'jina.executors.indexers.BaseExecutor', 'jina.executors.indexers.BaseIndexer', 'jina.executors.indexers.BaseKVIndexer', 'jina.executors.indexers.BaseVectorIndexer', 'jina.executors.indexers.CompoundExecutor', 'jina.executors.indexers.CompoundIndexer', 'jina.executors.encoders.BaseAudioEncoder', 'jina.executors.encoders.BaseEncoder', 'jina.executors.encoders.BaseExecutor', 'jina.executors.encoders.BaseImageEncoder', 'jina.executors.encoders.BaseNumericEncoder', 'jina.executors.encoders.BaseTextEncoder', 'jina.executors.encoders.BaseVideoEncoder', 'jina.executors.encoders.CompoundExecutor', 'jina.executors.encoders.PipelineEncoder', 'jina.executors.encoders.frameworks.BaseEncoder', 'jina.executors.encoders.frameworks.BaseMindsporeEncoder', 'jina.executors.encoders.frameworks.BaseOnnxEncoder', 'jina.executors.encoders.frameworks.BasePaddleEncoder', 'jina.executors.encoders.frameworks.BaseTFEncoder', 'jina.executors.encoders.frameworks.BaseTorchEncoder']. You can use `jina check` to list all executors and drivers
           JINA@7561[W]:due to the missing dependencies or bad implementations, ['jina.hub.encoders.image.ImagePaddlehubEncoder.BasePaddleEncoder', 'jina.hub.encoders.image.ImagePaddlehubEncoder.ImagePaddlehubEncoder', 'jina.hub.encoders.image.ImageTorchEncoder.BaseTorchEncoder', 'jina.hub.encoders.image.ImageTorchEncoder.ImageTorchEncoder', 'jina.hub.encoders.numeric.BaseNumericEncoder', 'jina.hub.encoders.numeric.TransformEncoder', 'jina.hub.crafters.image.ImageResizer.BaseCrafter', 'jina.hub.crafters.image.ImageResizer.ImageResizer', 'jina.hub.crafters.nlp.JiebaSegmenter.BaseSegmenter', 'jina.hub.crafters.nlp.JiebaSegmenter.JiebaSegmenter', 'jina.hub.crafters.image.ImageCropper.BaseCrafter', 'jina.hub.crafters.image.ImageCropper.ImageCropper', 'jina.hub.encoders.nlp.TransformerTorchEncoder.BaseEncoder', 'jina.hub.encoders.nlp.TransformerTorchEncoder.TransformerTorchEncoder', 'jina.hub.crafters.image.RandomImageCropper.BaseSegmenter', 'jina.hub.crafters.image.RandomImageCropper.RandomImageCropper', 'jina.hub.indexers.vector.MilvusIndexer.BaseVectorIndexer', 'jina.hub.indexers.vector.MilvusIndexer.MilvusIndexer', 'jina.hub.crafters.numeric.ArrayBytesReader.ArrayBytesReader', 'jina.hub.crafters.numeric.ArrayBytesReader.BaseCrafter', 'jina.hub.rankers.TfIdfRanker.Chunk2DocRanker', 'jina.hub.rankers.TfIdfRanker.TfIdfRanker', 'jina.hub.encoders.audio.ChromaPitchEncoder.BaseAudioEncoder', 'jina.hub.encoders.audio.ChromaPitchEncoder.ChromaPitchEncoder', 'jina.hub.indexers.vector.NGTIndexer.BaseNumpyIndexer', 'jina.hub.indexers.vector.NGTIndexer.NGTIndexer', 'jina.hub.encoders.image.ImageOnnxEncoder.BaseOnnxEncoder', 'jina.hub.encoders.image.ImageOnnxEncoder.ImageOnnxEncoder', 'jina.hub.encoders.nlp.TransformerTFEncoder.BaseEncoder', 'jina.hub.encoders.nlp.TransformerTFEncoder.TransformerTFEncoder', 'jina.hub.crafters.numeric.ArrayStringReader.ArrayStringReader', 'jina.hub.crafters.numeric.ArrayStringReader.BaseCrafter', 'jina.hub.crafters.audio.AudioReader.AudioReader', 'jina.hub.crafters.audio.AudioReader.BaseCrafter', 'jina.hub.crafters.nlp.SlidingWindowSegmenter.BaseSegmenter', 'jina.hub.crafters.nlp.SlidingWindowSegmenter.SlidingWindowSegmenter', 'jina.hub.crafters.image.FiveImageCropper.BaseSegmenter', 'jina.hub.crafters.image.FiveImageCropper.FiveImageCropper', 'jina.hub.rankers.BM25Ranker.BM25Ranker', 'jina.hub.rankers.BM25Ranker.Chunk2DocRanker', 'jina.hub.crafters.image.SlidingWindowImageCropper.BaseSegmenter', 'jina.hub.crafters.image.SlidingWindowImageCropper.SlidingWindowImageCropper', 'jina.hub.rankers.BiMatchRanker.BiMatchRanker', 'jina.hub.rankers.BiMatchRanker.Chunk2DocRanker', 'jina.hub.encoders.numeric.TSNEEncoder.BaseNumericEncoder', 'jina.hub.encoders.numeric.TSNEEncoder.TSNEEncoder', 'jina.hub.encoders.numeric.RandomSparseEncoder.RandomSparseEncoder', 'jina.hub.encoders.numeric.RandomSparseEncoder.TransformEncoder', 'jina.hub.crafters.audio.AudioSlicer.AudioSegmenter', 'jina.hub.crafters.audio.AudioSlicer.AudioSlicer', 'jina.hub.crafters.audio.AudioSlicer.BaseSegmenter', 'jina.hub.rankers.MinRanker.Chunk2DocRanker', 'jina.hub.rankers.MinRanker.MinRanker', 'jina.hub.crafters.image.ImageFlipper.BaseCrafter', 'jina.hub.crafters.image.ImageFlipper.ImageFlipper', 'jina.hub.indexers.vector.SptagIndexer.BaseNumpyIndexer', 'jina.hub.indexers.vector.SptagIndexer.SptagIndexer', 'jina.hub.indexers.vector.AnnoyIndexer.AnnoyIndexer', 'jina.hub.indexers.vector.AnnoyIndexer.BaseNumpyIndexer', 'jina.hub.encoders.nlp.LaserEncoder.BaseTorchEncoder', 'jina.hub.encoders.nlp.LaserEncoder.LaserEncoder', 'jina.hub.encoders.video.VideoPaddleEncoder.BasePaddleEncoder', 'jina.hub.encoders.video.VideoPaddleEncoder.VideoPaddleEncoder', 'jina.hub.encoders.image.CustomImageTorchEncoder.BaseTorchEncoder', 'jina.hub.encoders.image.CustomImageTorchEncoder.CustomImageTorchEncoder', 'jina.hub.rankers.MaxRanker.Chunk2DocRanker', 'jina.hub.rankers.MaxRanker.MaxRanker', 'jina.hub.crafters.image.ImageNormalizer.BaseCrafter', 'jina.hub.crafters.image.ImageNormalizer.ImageNormalizer', 'jina.hub.encoders.numeric.FeatureAgglomerationEncoder.FeatureAgglomerationEncoder', 'jina.hub.encoders.numeric.FeatureAgglomerationEncoder.TransformEncoder', 'jina.hub.encoders.audio.Wav2VecSpeechEncoder.BaseAudioEncoder', 'jina.hub.encoders.audio.Wav2VecSpeechEncoder.BaseTorchEncoder', 'jina.hub.encoders.audio.Wav2VecSpeechEncoder.Wav2VecSpeechEncoder', 'jina.hub.encoders.nlp.FlairTextEncoder.BaseTorchEncoder', 'jina.hub.encoders.nlp.FlairTextEncoder.FlairTextEncoder', 'jina.hub.crafters.audio.SlidingWindowAudioSlicer.AudioSegmenter', 'jina.hub.crafters.audio.SlidingWindowAudioSlicer.BaseSegmenter', 'jina.hub.crafters.audio.SlidingWindowAudioSlicer.SlidingWindowAudioSlicer', 'jina.hub.encoders.numeric.FastICAEncoder.FastICAEncoder', 'jina.hub.encoders.numeric.FastICAEncoder.TransformEncoder', 'jina.hub.indexers.vector.FaissIndexer.BaseNumpyIndexer', 'jina.hub.indexers.vector.FaissIndexer.FaissIndexer', 'jina.hub.crafters.audio.AudioNormalizer.AudioNormalizer', 'jina.hub.crafters.audio.AudioNormalizer.BaseCrafter', 'jina.hub.encoders.video.VideoTorchEncoder.BaseTorchEncoder', 'jina.hub.encoders.video.VideoTorchEncoder.BaseVideoEncoder', 'jina.hub.encoders.video.VideoTorchEncoder.VideoTorchEncoder', 'jina.hub.crafters.image.ImageReader.BaseCrafter', 'jina.hub.crafters.image.ImageReader.ImageReader', 'jina.hub.encoders.audio.MFCCTimbreEncoder.BaseAudioEncoder', 'jina.hub.encoders.audio.MFCCTimbreEncoder.ChromaPitchEncoder', 'jina.hub.encoders.audio.MFCCTimbreEncoder.MFCCTimbreEncoder', 'jina.hub.encoders.image.ImageKerasEncoder.BaseTFEncoder', 'jina.hub.encoders.image.ImageKerasEncoder.ImageKerasEncoder', 'jina.hub.indexers.vector.ScannIndexer.BaseNumpyIndexer', 'jina.hub.indexers.vector.ScannIndexer.ScannIndexer', 'jina.hub.indexers.keyvalue.LevelDBIndexer', 'jina.hub.crafters.image.CenterImageCropper.BaseCrafter', 'jina.hub.crafters.image.CenterImageCropper.CenterImageCropper', 'jina.hub.indexers.vector.NmsLibIndexer.BaseNumpyIndexer', 'jina.hub.indexers.vector.NmsLibIndexer.NmsLibIndexer', 'jina.hub.crafters.nlp.DeepSegmenter.BaseSegmenter', 'jina.hub.crafters.nlp.DeepSegmenter.DeepSegmenter', 'jina.hub.encoders.nlp.FarmTextEncoder.BaseTorchEncoder', 'jina.hub.encoders.nlp.FarmTextEncoder.FarmTextEncoder', 'jina.hub.encoders.numeric.IncrementalPCAEncoder.IncrementalPCAEncoder', 'jina.hub.encoders.numeric.IncrementalPCAEncoder.TransformEncoder', 'jina.hub.encoders.nlp.OneHotTextEncoder.BaseTextEncoder', 'jina.hub.encoders.nlp.OneHotTextEncoder.OneHotTextEncoder', 'jina.hub.encoders.nlp.UniversalSentenceEncoder.BaseTFEncoder', 'jina.hub.encoders.nlp.UniversalSentenceEncoder.UniversalSentenceEncoder', 'jina.hub.crafters.audio.AudioMonophoner.AudioMonophoner', 'jina.hub.crafters.audio.AudioMonophoner.BaseCrafter', 'jina.hub.encoders.image.BigTransferEncoder.BaseTFEncoder', 'jina.hub.encoders.image.BigTransferEncoder.BigTransferEncoder', 'jina.hub.crafters.image.TorchObjectDetectionSegmenter.BaseSegmenter', 'jina.hub.crafters.image.TorchObjectDetectionSegmenter.TorchObjectDetectionSegmenter', 'jina.hub.crafters.nlp.Sentencizer.BaseSegmenter', 'jina.hub.crafters.nlp.Sentencizer.Sentencizer', 'jina.hub.encoders.nlp.TextPaddlehubEncoder.BasePaddleEncoder', 'jina.hub.encoders.nlp.TextPaddlehubEncoder.TextPaddlehubEncoder', 'jina.hub.encoders.numeric.RandomGaussianEncoder.RandomGaussianEncoder', 'jina.hub.encoders.numeric.RandomGaussianEncoder.TransformEncoder'] can not be imported if you are using these executors/drivers, they wont work. You can use `jina check` to list all executors and drivers
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from jina.flow import Flow
  File "/usr/local/lib/python3.8/dist-packages/jina/flow/__init__.py", line 23, in <module>
    from ..peapods.pod import SocketType, FlowPod, GatewayFlowPod
  File "/usr/local/lib/python3.8/dist-packages/jina/peapods/pod.py", line 13, in <module>
    from .gateway import GatewayPea, RESTGatewayPea
  File "/usr/local/lib/python3.8/dist-packages/jina/peapods/gateway.py", line 13, in <module>
    from .pea import BasePea
  File "/usr/local/lib/python3.8/dist-packages/jina/peapods/pea.py", line 15, in <module>
    from .zmq import send_ctrl_message, Zmqlet, ZmqStreamlet
  File "/usr/local/lib/python3.8/dist-packages/jina/peapods/zmq.py", line 22, in <module>
    from ..proto import jina_pb2, is_data_request
  File "/usr/local/lib/python3.8/dist-packages/jina/proto/__init__.py", line 8, in <module>
    from .jina_pb2 import Request
  File "/usr/local/lib/python3.8/dist-packages/jina/proto/jina_pb2.py", line 21, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
```

This is when running "python3 app.py -t index"

```
  File "app.py", line 32
    f'unknown task: {task}. A valid task is `index` or `query` or `query_restful`.')
                                                                                  ^
SyntaxError: invalid syntax
```

**Comment by ArturTanona** [comment]
Hi, thanks for the question. Could you tell me what is the version of Jina you are working on? Is it 0.5.0? Could you send me the output of `jina --version` command?

**Comment by OSINTAI** [comment]
Thanks.
I am using Jina 0.5.0 and this is the output of `jina --version
`




`root@ai:/home/ai/Documents/transformers-for-lawyers/search_engine# jina --version
           JINA@35007[E]:theses modules or classes can not be imported ['jina.drivers.querylang.filter', 'jina.drivers.querylang.queryset.lookup', 'jina.drivers.reduce', 'jina.drivers.querylang', 'jina.drivers.querylang.sort', 'jina.drivers.convert', 'jina.drivers.querylang.queryset.dunderkey', 'jina.drivers.control', 'jina.drivers.querylang.reverse', 'jina.drivers.querylang.queryset.helper', 'jina.drivers.search', 'jina.drivers.encode', 'jina.drivers.helper', 'jina.drivers.craft', 'jina.drivers.querylang.queryset', 'jina.drivers.rank', 'jina.drivers.querylang.slice', 'jina.drivers.index', 'jina.drivers.querylang.select']. You can use `jina check` to list all executors and drivers
           JINA@35007[E]:theses modules or classes can not be imported ['jina.executors.rankers.BaseExecutor', 'jina.executors.rankers.BaseRanker', 'jina.executors.rankers.Chunk2DocRanker', 'jina.executors.clients.BaseClientExecutor', 'jina.executors.clients.BaseExecutor', 'jina.executors.clients.BaseTFServingClientExecutor', 'jina.executors.encoders.tfserving.BaseEncoder', 'jina.executors.encoders.tfserving.BaseTFServingClientEncoder', 'jina.executors.encoders.tfserving.BaseTFServingClientExecutor', 'jina.executors.encoders.tfserving.UnaryTFServingClientEncoder', 'jina.executors.encoders.BaseAudioEncoder', 'jina.executors.encoders.BaseEncoder', 'jina.executors.encoders.BaseExecutor', 'jina.executors.encoders.BaseImageEncoder', 'jina.executors.encoders.BaseNumericEncoder', 'jina.executors.encoders.BaseTextEncoder', 'jina.executors.encoders.BaseVideoEncoder', 'jina.executors.encoders.CompoundExecutor', 'jina.executors.encoders.PipelineEncoder', 'jina.executors.indexers.BaseExecutor', 'jina.executors.indexers.BaseIndexer', 'jina.executors.indexers.BaseKVIndexer', 'jina.executors.indexers.BaseVectorIndexer', 'jina.executors.indexers.CompoundExecutor', 'jina.executors.indexers.CompoundIndexer', 'jina.executors.indexers.vector.BaseNumpyIndexer', 'jina.executors.indexers.vector.BaseVectorIndexer', 'jina.executors.indexers.vector.NumpyIndexer', 'jina.executors.encoders.numeric.BaseNumericEncoder', 'jina.executors.encoders.numeric.TransformEncoder', 'jina.executors.crafters.BaseCrafter', 'jina.executors.crafters.BaseExecutor', 'jina.executors.crafters.BaseSegmenter', 'jina.executors.indexers.keyvalue', 'jina.executors.compound.BaseExecutor', 'jina.executors.compound.CompoundExecutor', 'jina.executors.encoders.frameworks.BaseEncoder', 'jina.executors.encoders.frameworks.BaseMindsporeEncoder', 'jina.executors.encoders.frameworks.BaseOnnxEncoder', 'jina.executors.encoders.frameworks.BasePaddleEncoder', 'jina.executors.encoders.frameworks.BaseTFEncoder', 'jina.executors.encoders.frameworks.BaseTorchEncoder']. You can use `jina check` to list all executors and drivers
           JINA@35007[W]:due to the missing dependencies or bad implementations, ['jina.hub.crafters.numeric.ArrayBytesReader.ArrayBytesReader', 'jina.hub.crafters.numeric.ArrayBytesReader.BaseCrafter', 'jina.hub.rankers.BiMatchRanker.BiMatchRanker', 'jina.hub.rankers.BiMatchRanker.Chunk2DocRanker', 'jina.hub.indexers.vector.NmsLibIndexer.BaseNumpyIndexer', 'jina.hub.indexers.vector.NmsLibIndexer.NmsLibIndexer', 'jina.hub.encoders.image.BigTransferEncoder.BaseTFEncoder', 'jina.hub.encoders.image.BigTransferEncoder.BigTransferEncoder', 'jina.hub.encoders.numeric.BaseNumericEncoder', 'jina.hub.encoders.numeric.TransformEncoder', 'jina.hub.encoders.nlp.FarmTextEncoder.BaseTorchEncoder', 'jina.hub.encoders.nlp.FarmTextEncoder.FarmTextEncoder', 'jina.hub.indexers.vector.AnnoyIndexer.AnnoyIndexer', 'jina.hub.indexers.vector.AnnoyIndexer.BaseNumpyIndexer', 'jina.hub.crafters.audio.SlidingWindowAudioSlicer.AudioSegmenter', 'jina.hub.crafters.audio.SlidingWindowAudioSlicer.BaseSegmenter', 'jina.hub.crafters.audio.SlidingWindowAudioSlicer.SlidingWindowAudioSlicer', 'jina.hub.encoders.nlp.TextPaddlehubEncoder.BasePaddleEncoder', 'jina.hub.encoders.nlp.TextPaddlehubEncoder.TextPaddlehubEncoder', 'jina.hub.encoders.image.ImageTorchEncoder.BaseTorchEncoder', 'jina.hub.encoders.image.ImageTorchEncoder.ImageTorchEncoder', 'jina.hub.encoders.audio.MFCCTimbreEncoder.BaseAudioEncoder', 'jina.hub.encoders.audio.MFCCTimbreEncoder.ChromaPitchEncoder', 'jina.hub.encoders.audio.MFCCTimbreEncoder.MFCCTimbreEncoder', 'jina.hub.crafters.audio.AudioMonophoner.AudioMonophoner', 'jina.hub.crafters.audio.AudioMonophoner.BaseCrafter', 'jina.hub.crafters.image.RandomImageCropper.BaseSegmenter', 'jina.hub.crafters.image.RandomImageCropper.RandomImageCropper', 'jina.hub.indexers.vector.MilvusIndexer.BaseVectorIndexer', 'jina.hub.indexers.vector.MilvusIndexer.MilvusIndexer', 'jina.hub.crafters.image.ImageNormalizer.BaseCrafter', 'jina.hub.crafters.image.ImageNormalizer.ImageNormalizer', 'jina.hub.encoders.image.CustomImageTorchEncoder.BaseTorchEncoder', 'jina.hub.encoders.image.CustomImageTorchEncoder.CustomImageTorchEncoder', 'jina.hub.indexers.keyvalue.LevelDBIndexer', 'jina.hub.indexers.vector.NGTIndexer.BaseNumpyIndexer', 'jina.hub.indexers.vector.NGTIndexer.NGTIndexer', 'jina.hub.crafters.nlp.DeepSegmenter.BaseSegmenter', 'jina.hub.crafters.nlp.DeepSegmenter.DeepSegmenter', 'jina.hub.encoders.image.ImageOnnxEncoder.BaseOnnxEncoder', 'jina.hub.encoders.image.ImageOnnxEncoder.ImageOnnxEncoder', 'jina.hub.indexers.vector.FaissIndexer.BaseNumpyIndexer', 'jina.hub.indexers.vector.FaissIndexer.FaissIndexer', 'jina.hub.rankers.MinRanker.Chunk2DocRanker', 'jina.hub.rankers.MinRanker.MinRanker', 'jina.hub.encoders.audio.Wav2VecSpeechEncoder.BaseAudioEncoder', 'jina.hub.encoders.audio.Wav2VecSpeechEncoder.BaseTorchEncoder', 'jina.hub.encoders.audio.Wav2VecSpeechEncoder.Wav2VecSpeechEncoder', 'jina.hub.encoders.numeric.TSNEEncoder.BaseNumericEncoder', 'jina.hub.encoders.numeric.TSNEEncoder.TSNEEncoder', 'jina.hub.crafters.image.ImageFlipper.BaseCrafter', 'jina.hub.crafters.image.ImageFlipper.ImageFlipper', 'jina.hub.encoders.numeric.IncrementalPCAEncoder.IncrementalPCAEncoder', 'jina.hub.encoders.numeric.IncrementalPCAEncoder.TransformEncoder', 'jina.hub.encoders.nlp.TransformerTFEncoder.BaseEncoder', 'jina.hub.encoders.nlp.TransformerTFEncoder.TransformerTFEncoder', 'jina.hub.crafters.nlp.JiebaSegmenter.BaseSegmenter', 'jina.hub.crafters.nlp.JiebaSegmenter.JiebaSegmenter', 'jina.hub.crafters.image.ImageReader.BaseCrafter', 'jina.hub.crafters.image.ImageReader.ImageReader', 'jina.hub.crafters.image.CenterImageCropper.BaseCrafter', 'jina.hub.crafters.image.CenterImageCropper.CenterImageCropper', 'jina.hub.encoders.video.VideoTorchEncoder.BaseTorchEncoder', 'jina.hub.encoders.video.VideoTorchEncoder.BaseVideoEncoder', 'jina.hub.encoders.video.VideoTorchEncoder.VideoTorchEncoder', 'jina.hub.encoders.numeric.RandomGaussianEncoder.RandomGaussianEncoder', 'jina.hub.encoders.numeric.RandomGaussianEncoder.TransformEncoder', 'jina.hub.encoders.nlp.FlairTextEncoder.BaseTorchEncoder', 'jina.hub.encoders.nlp.FlairTextEncoder.FlairTextEncoder', 'jina.hub.encoders.image.ImageKerasEncoder.BaseTFEncoder', 'jina.hub.encoders.image.ImageKerasEncoder.ImageKerasEncoder', 'jina.hub.crafters.audio.AudioNormalizer.AudioNormalizer', 'jina.hub.crafters.audio.AudioNormalizer.BaseCrafter', 'jina.hub.crafters.image.TorchObjectDetectionSegmenter.BaseSegmenter', 'jina.hub.crafters.image.TorchObjectDetectionSegmenter.TorchObjectDetectionSegmenter', 'jina.hub.indexers.vector.SptagIndexer.BaseNumpyIndexer', 'jina.hub.indexers.vector.SptagIndexer.SptagIndexer', 'jina.hub.encoders.nlp.OneHotTextEncoder.BaseTextEncoder', 'jina.hub.encoders.nlp.OneHotTextEncoder.OneHotTextEncoder', 'jina.hub.crafters.nlp.Sentencizer.BaseSegmenter', 'jina.hub.crafters.nlp.Sentencizer.Sentencizer', 'jina.hub.crafters.image.FiveImageCropper.BaseSegmenter', 'jina.hub.crafters.image.FiveImageCropper.FiveImageCropper', 'jina.hub.encoders.nlp.UniversalSentenceEncoder.BaseTFEncoder', 'jina.hub.encoders.nlp.UniversalSentenceEncoder.UniversalSentenceEncoder', 'jina.hub.rankers.BM25Ranker.BM25Ranker', 'jina.hub.rankers.BM25Ranker.Chunk2DocRanker', 'jina.hub.encoders.numeric.FastICAEncoder.FastICAEncoder', 'jina.hub.encoders.numeric.FastICAEncoder.TransformEncoder', 'jina.hub.crafters.audio.AudioReader.AudioReader', 'jina.hub.crafters.audio.AudioReader.BaseCrafter', 'jina.hub.encoders.image.ImagePaddlehubEncoder.BasePaddleEncoder', 'jina.hub.encoders.image.ImagePaddlehubEncoder.ImagePaddlehubEncoder', 'jina.hub.crafters.image.ImageResizer.BaseCrafter', 'jina.hub.crafters.image.ImageResizer.ImageResizer', 'jina.hub.encoders.numeric.RandomSparseEncoder.RandomSparseEncoder', 'jina.hub.encoders.numeric.RandomSparseEncoder.TransformEncoder', 'jina.hub.rankers.TfIdfRanker.Chunk2DocRanker', 'jina.hub.rankers.TfIdfRanker.TfIdfRanker', 'jina.hub.crafters.image.SlidingWindowImageCropper.BaseSegmenter', 'jina.hub.crafters.image.SlidingWindowImageCropper.SlidingWindowImageCropper', 'jina.hub.crafters.audio.AudioSlicer.AudioSegmenter', 'jina.hub.crafters.audio.AudioSlicer.AudioSlicer', 'jina.hub.crafters.audio.AudioSlicer.BaseSegmenter', 'jina.hub.crafters.numeric.ArrayStringReader.ArrayStringReader', 'jina.hub.crafters.numeric.ArrayStringReader.BaseCrafter', 'jina.hub.crafters.image.ImageCropper.BaseCrafter', 'jina.hub.crafters.image.ImageCropper.ImageCropper', 'jina.hub.encoders.nlp.LaserEncoder.BaseTorchEncoder', 'jina.hub.encoders.nlp.LaserEncoder.LaserEncoder', 'jina.hub.encoders.audio.ChromaPitchEncoder.BaseAudioEncoder', 'jina.hub.encoders.audio.ChromaPitchEncoder.ChromaPitchEncoder', 'jina.hub.encoders.video.VideoPaddleEncoder.BasePaddleEncoder', 'jina.hub.encoders.video.VideoPaddleEncoder.VideoPaddleEncoder', 'jina.hub.rankers.MaxRanker.Chunk2DocRanker', 'jina.hub.rankers.MaxRanker.MaxRanker', 'jina.hub.encoders.numeric.FeatureAgglomerationEncoder.FeatureAgglomerationEncoder', 'jina.hub.encoders.numeric.FeatureAgglomerationEncoder.TransformEncoder', 'jina.hub.indexers.vector.ScannIndexer.BaseNumpyIndexer', 'jina.hub.indexers.vector.ScannIndexer.ScannIndexer', 'jina.hub.encoders.nlp.TransformerTorchEncoder.BaseEncoder', 'jina.hub.encoders.nlp.TransformerTorchEncoder.TransformerTorchEncoder', 'jina.hub.crafters.nlp.SlidingWindowSegmenter.BaseSegmenter', 'jina.hub.crafters.nlp.SlidingWindowSegmenter.SlidingWindowSegmenter'] can not be imported if you are using these executors/drivers, they wont work. You can use `jina check` to list all executors and drivers
0.5.0
`

**Comment by ArturTanona** [comment]
Many thanks. Please checkout to this [branch ](https://github.com/ArturTan/transformers-for-lawyers/tree/at-add-dummy-data) and run the commands:

`pip install -r requirements.txt`
and 
`python3.8 app.py -t index`

BR
